// 사용자 제공 Preset(all) 이관
const all = {
  severe_burnout: [
    {
      id: "challenge",
      name: "도전형",
      emoji: "⚡",
      subtitle: "새로운 활동으로 돌파",
      tagline: "적극적 자극을 통한 회복",
      type: "제주 어드벤처 힐링",
      duration: "5박 6일",
      location: "제주 동쪽",
      focus: ["새로운 경험", "신체 활동", "성취감"],
      mainActivities: ["서핑 입문", "스쿠버", "패러글라이딩", "자전거"],
      suitable: "도전 선호",
      cost: "120-150만원",
    },
    {
      id: "maintain",
      name: "유지형",
      emoji: "🌊",
      subtitle: "균형잡힌 회복",
      tagline: "휴식과 활동의 조화",
      type: "제주 남쪽 해안 힐링",
      duration: "7박 8일",
      location: "서귀포",
      focus: ["신체 회복", "인지 휴식", "정서 재연결"],
      mainActivities: ["해변 산책", "감각 재연결", "도자기"],
      suitable: "중간 자극",
      cost: "150-200만원",
    },
    {
      id: "harmony",
      name: "화해형",
      emoji: "🕊️",
      subtitle: "내면과의 화해",
      tagline: "완전한 고요 속 치유",
      type: "제주 서쪽 명상 리트릿",
      duration: "7박 8일",
      location: "한림-애월",
      focus: ["명상/요가", "침묵", "자기연민"],
      mainActivities: ["침묵 수행", "명상", "일기"],
      suitable: "고요 선호",
      cost: "180-220만원",
    },
  ],
  energy_depletion: [
    {
      id: "challenge",
      name: "도전형",
      emoji: "🏔️",
      subtitle: "정복으로 회복",
      tagline: "지리산 종주",
      type: "지리산 등정",
      duration: "3박 4일",
      location: "지리산",
      focus: ["체력", "성취", "자신감"],
      mainActivities: ["종주", "산장", "일출"],
      suitable: "목표 달성형",
      cost: "50-70만원",
    },
    {
      id: "maintain",
      name: "유지형",
      emoji: "🌲",
      subtitle: "자연 에너지",
      tagline: "숲 치유",
      type: "지리산 숲 충전",
      duration: "4박 5일",
      location: "피아골",
      focus: ["피톤치드", "햇볕"],
      mainActivities: ["숲 치유", "계곡 걷기"],
      suitable: "천천히 회복",
      cost: "60-80만원",
    },
    {
      id: "harmony",
      name: "화해형",
      emoji: "🧘",
      subtitle: "고요 속 재충전",
      tagline: "템플스테이",
      type: "산사 리트릿",
      duration: "4박 5일",
      location: "해인사/송광사",
      focus: ["명상", "발우공양"],
      mainActivities: ["참선", "울력", "차담"],
      suitable: "정신적 회복",
      cost: "30-50만원",
    },
  ],
  relationship_deficit: [
    {
      id: "challenge",
      name: "도전형",
      emoji: "🎭",
      subtitle: "적극적 관계",
      tagline: "그룹 활동",
      type: "제주 그룹 트레킹",
      duration: "3박 4일",
      location: "올레길",
      focus: ["공동 목표", "교류"],
      mainActivities: ["트레킹", "캠프파이어"],
      suitable: "활동형",
      cost: "50-70만원",
    },
    {
      id: "maintain",
      name: "유지형",
      emoji: "🏘️",
      subtitle: "안전한 커뮤니티",
      tagline: "부담 없는 연결",
      type: "전주 한옥 스테이",
      duration: "3박 4일",
      location: "전주",
      focus: ["소규모 교류"],
      mainActivities: ["공동 식사", "공예"],
      suitable: "천천히 연결",
      cost: "40-60만원",
    },
    {
      id: "harmony",
      name: "화해형",
      emoji: "📖",
      subtitle: "나와의 관계",
      tagline: "독서 리트릿",
      type: "강화도 독서",
      duration: "3박 4일",
      location: "강화도",
      focus: ["자기 이해"],
      mainActivities: ["산책", "독서", "성찰"],
      suitable: "내향 선호",
      cost: "30-50만원",
    },
  ],
  meaning_loss: [
    {
      id: "challenge",
      name: "도전형",
      emoji: "🚴",
      subtitle: "도전으로 의미 찾기",
      tagline: "4대강 자전거",
      type: "자전거 여행",
      duration: "5박 6일",
      location: "한강-낙동",
      focus: ["목표", "경험"],
      mainActivities: ["라이딩", "탐방"],
      suitable: "행동형",
      cost: "70-100만원",
    },
    {
      id: "maintain",
      name: "유지형",
      emoji: "🚶",
      subtitle: "걸으며 찾기",
      tagline: "걷기 명상",
      type: "제주 올레 의미 탐색",
      duration: "5박 6일",
      location: "제주",
      focus: ["성찰"],
      mainActivities: ["순례", "일기"],
      suitable: "사유형",
      cost: "80-100만원",
    },
    {
      id: "harmony",
      name: "화해형",
      emoji: "✍️",
      subtitle: "글쓰기로 발견",
      tagline: "작가의 집",
      type: "강릉/통영",
      duration: "5박 6일",
      location: "강릉/통영",
      focus: ["글쓰기"],
      mainActivities: ["자서전", "시"],
      suitable: "창작 관심",
      cost: "60-80만원",
    },
  ],
  overstimulation: [
    {
      id: "challenge",
      name: "도전형",
      emoji: "⛵",
      subtitle: "아날로그 모험",
      tagline: "요트 여행",
      type: "남해 무인도 투어",
      duration: "3박 4일",
      location: "남해",
      focus: ["디톡스"],
      mainActivities: ["요트", "낚시"],
      suitable: "새로움",
      cost: "150-200만원",
    },
    {
      id: "maintain",
      name: "유지형",
      emoji: "🏝️",
      subtitle: "섬의 단순함",
      tagline: "디지털 차단",
      type: "울릉도 디톡스",
      duration: "4박 5일",
      location: "울릉도",
      focus: ["느린 시간"],
      mainActivities: ["산책", "별 관측"],
      suitable: "완전 차단",
      cost: "90-120만원",
    },
    {
      id: "harmony",
      name: "화해형",
      emoji: "🏞️",
      subtitle: "시골 생활",
      tagline: "농촌 스테이",
      type: "영양 두들마을",
      duration: "5박 6일",
      location: "경북 영양",
      focus: ["자급자족"],
      mainActivities: ["농사", "전통 음식"],
      suitable: "단순 노동",
      cost: "40-60만원",
    },
  ],
  anxiety_tension: [
    {
      id: "challenge",
      name: "도전형",
      emoji: "🏄",
      subtitle: "극복으로 감소",
      tagline: "두려움 직면",
      type: "양양 서핑",
      duration: "3박 4일",
      location: "양양",
      focus: ["집중"],
      mainActivities: ["레슨", "요가"],
      suitable: "활동형",
      cost: "60-80만원",
    },
    {
      id: "maintain",
      name: "유지형",
      emoji: "🧘",
      subtitle: "이완 학습",
      tagline: "호흡과 요가",
      type: "요가 리트릿",
      duration: "3박 4일",
      location: "보령/양양",
      focus: ["명상"],
      mainActivities: ["하타 요가", "바디스캔"],
      suitable: "체계적 학습",
      cost: "50-70만원",
    },
    {
      id: "harmony",
      name: "화해형",
      emoji: "🎨",
      subtitle: "창작 표현",
      tagline: "아트 테라피",
      type: "제주 미술 치유",
      duration: "4박 5일",
      location: "제주 애월",
      focus: ["감정 표현"],
      mainActivities: ["그림", "도자기"],
      suitable: "예술 관심",
      cost: "80-100만원",
    },
  ],
  mild_stress: [
    {
      id: "challenge",
      name: "도전형",
      emoji: "🎿",
      subtitle: "짜릿한 재충전",
      tagline: "액티비티",
      type: "가평 액티비티",
      duration: "1박 2일",
      location: "가평",
      focus: ["스릴"],
      mainActivities: ["짚라인", "번지"],
      suitable: "자극 선호",
      cost: "20-30만원",
    },
    {
      id: "maintain",
      name: "유지형",
      emoji: "🌊",
      subtitle: "편안한 주말",
      tagline: "해변에서 쉬기",
      type: "강릉/속초",
      duration: "2박 3일",
      location: "강릉",
      focus: ["휴식"],
      mainActivities: ["산책", "카페"],
      suitable: "휴식 선호",
      cost: "30-50만원",
    },
    {
      id: "harmony",
      name: "화해형",
      emoji: "♨️",
      subtitle: "온천 힐링",
      tagline: "따뜻한 물",
      type: "이천/아산 온천",
      duration: "1박 2일",
      location: "이천",
      focus: ["이완"],
      mainActivities: ["온천", "마사지"],
      suitable: "몸 이완",
      cost: "20-40만원",
    },
  ],
  healthy_maintenance: [
    {
      id: "challenge",
      name: "도전형",
      emoji: "🏃",
      subtitle: "새 취미 도전",
      tagline: "배우고 성장",
      type: "월간 활동",
      duration: "월별",
      location: "서울/근교",
      focus: ["배움"],
      mainActivities: ["클라이밍", "댄스"],
      suitable: "성장 지향",
      cost: "월10-20만원",
    },
    {
      id: "maintain",
      name: "유지형",
      emoji: "🌳",
      subtitle: "자연과 함께",
      tagline: "정기 자연 접촉",
      type: "월간 나들이",
      duration: "월1회",
      location: "시즌별",
      focus: ["자연", "휴식"],
      mainActivities: ["명소", "산책"],
      suitable: "꾸준함",
      cost: "월5-15만원",
    },
    {
      id: "harmony",
      name: "화해형",
      emoji: "📚",
      subtitle: "내면 성장",
      tagline: "명상/독서",
      type: "주간 루틴",
      duration: "매주",
      location: "집/동네",
      focus: ["성찰"],
      mainActivities: ["명상모임", "독서"],
      suitable: "조용한 성향",
      cost: "월5-10만원",
    },
  ],
};

export function getPrescriptionOptions(diagnosisType) {
  return all[diagnosisType] || all.healthy_maintenance;
}

export default all;
